### ISSUE TITLE
How does performance compare with go?

### ISSUE THREAD

**Issue by trosel** [chr4/writing_an_interpreter_in_rust#12]
This info would be great for someone that is deciding on which language to use for writing an interpreter. Perhaps they want to weigh the pros/cons of using Rust after they've already learned how to do it in Go.

Is there a good way to measure this?

**Comment by chr4** [comment]
I've conducted some basic tests (running comparable test suites in a loop and compare the execution times), and the Rust version was a lot faster. Mostly because of [some idiomatic changes](https://chr4.org/blog/2016/12/17/writing-an-interpreter-in-rust-part-2/).

The purpose of the book "Writing An Interpreter In Go" however, is to be educational. It tries to teach the basic principles of implementing a programming language with code that is easy to understand and easy to transfer to other use cases. The purpose of Monkey, as far as I understood the author, was not performance, but education.
